- name: "Restart avahi-daemon service"
  ansible.builtin.service:
    name: avahi-daemon
    state: restarted
  become: true
  become_user: root
  listen: "restart_avahi_services"
  when: (ansible_os_family == "Archlinux") or
        (ansible_os_family == "FreeBSD")

- name: "Restart avahi-dnsconfd service"
  ansible.builtin.service:
    name: avahi-dnsconfd
    state: restarted
  become: true
  become_user: root
  listen: "restart_avahi_services"
  when: (ansible_os_family == "FreeBSD")

- name: "Restart dbus service"
  ansible.builtin.service:
    name: dbus
    state: restarted
  become: true
  become_user: root
  listen: "restart_avahi_services"
  when: (ansible_os_family == "FreeBSD")

