# See https://loga.us/2020/09/02/avahi-in-freebsd/

- name: "In '{{ nsswitch_conf_path }}', make nss-mdns authoritative for avahi's .local domain"
  ansible.builtin.lineinfile:
    path: "{{ nsswitch_conf_path }}"
    regexp: >-
      ^hosts:
    line: >-
      hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4
    state: present
    create: no
    backrefs: yes
    backup: yes
  become: true
  become_user: root
  notify:
    - set_avahi_config_changed
    - restart_avahi_daemon
    - restart_avahi_dnsconfd

