# See https://loga.us/2020/09/02/avahi-in-freebsd/

- name: "Install the 'nss_mdns' hostname resolution package"
  ansible.builtin.package:
    name: nss_mdns
    state: present
  become: true
  become_user: root
  notify: "{{ handler_to_restart_avahi_services }}"

- name: "Ensure 'avahi-dnsconfd' service is started, and enable it to start at boot"
  ansible.builtin.service:
    name: avahi-dnsconfd
    state: started
    enabled: true
  become: true
  become_user: root
  notify: "{{ handler_to_restart_avahi_services }}"

- name: "In '{{ nsswitch_conf_path }}', make nss-mdns authoritative for avahi's .local domain"
  ansible.builtin.lineinfile:
    path: "{{ nsswitch_conf_path }}"
    regexp: >-
      ^hosts:
    line: >-
      hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4
    state: present
    create: false
    backrefs: true
    backup: true
  become: true
  become_user: root
  notify: "{{ handler_to_restart_avahi_services }}"

