# See https://loga.us/2020/09/02/avahi-in-freebsd/

- name: "Install the 'avahi-app' service-discovery package"
  ansible.builtin.package:
    name: avahi-app
    state: present
  become: true
  become_user: root
  notify:
    - set_avahi_config_changed
    - restart_avahi_daemon
    - restart_avahi_dnsconfd

- name: "Install the 'nss_mdns' hostname resolution package"
  ansible.builtin.package:
    name: nss_mdns
    state: present
  become: true
  become_user: root
  notify:
    - set_avahi_config_changed
    - restart_avahi_daemon
    - restart_avahi_dnsconfd
  when: enable_host_discovery_service

- name: "Ensure 'dbus' service is started, and enable it to start at boot"
  ansible.builtin.service:
    name: dbus
    state: started
    enabled: yes
  become: true
  become_user: root
  notify:
    - set_avahi_config_changed
    - restart_avahi_daemon
    - restart_avahi_dnsconfd

- name: "Ensure 'avahi-daemon' service is started, and enable it to start at boot"
  ansible.builtin.service:
    name: avahi-daemon
    state: started
    enabled: yes
  become: true
  become_user: root
  notify: set_avahi_config_changed

- name: "Ensure 'avahi-dnsconfd' service is started, and enable it to start at boot"
  ansible.builtin.service:
    name: avahi-dnsconfd
    state: started
    enabled: yes
  become: true
  become_user: root
  notify: set_avahi_config_changed
  when: enable_host_discovery_service

